### ISSUE TITLE
Natron is deprecated in FreeBSD

### ISSUE THREAD

**Issue by rodlie** [NatronGitHub/NatronGitHub-legacy-website#12]
https://www.freshports.org/graphics/natron/

FreeBSD does not support Qt4 anymore, we should probably remove the download info regarding FreeBSD until this is resolved?

**Comment by devernay** [comment]
that's a pretty bad move from FreeBSD
Just invited you to be a member of the web team, so you can correct this

**Comment by rodlie** [comment]
More and more systems are dropping Qt4, nothing we can do about it.

RHEL/CentOS and Slackware are pretty much the only systems that still support Qt4.

**Comment by rodlie** [comment]
I could maintain the old qt4 ports from FreeBSD as an overlay or something in a separate repo? Would be low maintenance.

I will also try to push the threadpool patch into Slackware (would be a great devkit, has the Qt version we want and has GCC9 etc out-of-the-box) , and maybe some other distros.

**Comment by blackearth2014** [comment]
Great
