### ISSUE TITLE
natron.fr status

### ISSUE THREAD

**Issue by rodlie** [NatronGitHub/NatronGitHub-legacy-website#13]
Something I can fix?

**Comment by blackearth2014** [comment]
Please do Ole and welcome back.

**Comment by rodlie** [comment]
@devernay point DNS (`www.natron.fr` + ``natron.fr`` (should be a redirect to ``www.natron.fr``))to `NatronGitHub.github.io` (not http(s)), then enable ``www.natron.fr`` (you can't use ``natron.fr`` directly) in the settings in this repo.

**Comment by rodlie** [comment]
Also note that you can enable website on individual repo and it will show up as https://natron.fr/<REPO_NAME>, example https://natron.fr/openfx-misc will show the README.md from openfx-misc. A nice feature

**Comment by devernay** [comment]
I think the github web site should be the official one. Google searches point to this, so there is no need to register another domain. Please leave this domain as the official one.

**Comment by rodlie** [comment]
ok
