### ISSUE TITLE
Website Refresh 2020

### ISSUE THREAD

**Issue by rodlie** [NatronGitHub/NatronGitHub-legacy-website#14]
Should I just modify the raw html or do you use some kind of generator for content?

**Comment by blackearth2014** [comment]
Raw HTML I believe

**Comment by rodlie** [comment]
Ok, thanks.

We will then need to make some adjustment, I don't want to maintain the layout/template over multiple html's. 

TODO: use a generator

**Comment by rodlie** [comment]
I forked the site and built a usable framework so anyone can edit the site:

* https://rodlie.github.io/NatronGitHub.github.io/
* https://github.com/rodlie/NatronGitHub.github.io
* https://github.com/rodlie/NatronGitHub.github.io/tree/master/_posts

Now everything is in markdown and we can have as many pages, blogs, news etc as we want, like a "real" website :)

I just started, so only the frontpage works, but it shouldn't take too long to finish.

**Comment by blackearth2014** [comment]
Good job

**Comment by rodlie** [comment]
It's a start, still stuff to do. Will work on it during the holidays. Would love help on text content.

**Comment by blackearth2014** [comment]
What kind of text are you looking for?

**Comment by rodlie** [comment]
I will write down a list (TODO).

**Comment by blackearth2014** [comment]
Cool breeze

**Comment by Shrinks99** [comment]
So this is a thing I could actually help to bring to life.  More than happy to help set up the new Jekyll site!

I can't promise a timeline, I'm always busy with design school but come May I should have some more time on my hands when I'm not working.

**Comment by rodlie** [comment]
Hi, and sorry for the late reply. I have already started the work at https://rodlie.github.io/NatronGitHub.github.io/ 

If you would like to help I would advise you to use my fork https://github.com/rodlie/NatronGitHub.github.io 

I'm a bit busy with other things this weekend, but I can dedicate some hours next week to finish (my part of) the website.

**Comment by Shrinks99** [comment]
I've had a look at this and there are a few major things I'd change with regards to how the website is made with Jekyll.

Personally I don't love using pre-made Jekyll themes and I'd ditch minima over creating some custom SASS for the styling as Jekyll has a SASS pre-processor built in.  Moving the CSS out of an in-line style and making the rest with a grid system and custom CSS would definitely be the way to go IMO.

There's a lot of metadata tags that aren't currently set up but I have templates for these set up for my [personal website](https://wilkinson.graphics) so I can totally copy those over and set them up here.  I've given you collaborator access to my website's repo so you can see how I manage these things (I keep it private because I don't wanna deal with licensing haha).

Setting up the github-pages bundle so things work as expected when GitHub generates the website is also recommended.  This means to run Jekyll you'd run `bundle exec Jekyll serve` to run all the various bits and bobs that GitHub pages can run when compiling and serving your website.

I'm down to start with these things and then move onto some larger design decisions down the road.  I'm down to fork it and submit as PRs (though I kinda hate having to fetch upstream repos and ensure things work all the time) or if you'd like to add me as a collaborator and I can submit PRs that way that would be cool too.

**Comment by devernay** [comment]
@Shrinks99 Great! as long as the content is still there and maintenance is easy, I have no issue with that kind of upgrade

**Comment by Shrinks99** [comment]
@devernay Content will be there and maintenance should be _easier!_

~~I've added you onto my personal site repo as well if you'd like to see how I plan on tackling this one in a similar fashion.~~  Have cancelled these and just implemented things haha, check out https://github.com/Shrinks99/NatronGitHub.github.io instead.  Bundler is implemented properly and SASS is setup, I've ditched a lot of the current styling and am in the process of re-designing the homepage right now after removing the existing theme.  Hopefully I'll be back at the point where things were visually this week!

You can view my current progress here: https://wilkinson.graphics/NatronGitHub.github.io/

**Comment by Shrinks99** [comment]
Bit of an update, I've made some decent headway into the homepage!  Still not sold on the hero section (I just exported a version of the spaceship project for the background) but I'm sure we can put something better together for that, the current one is pretty good but it is a little dated.

The downloads section is all set up to download the latest version from GitHub as long as a release post is made on the website which is pretty fancy, you should never have to update any of those links manually!

![Screenshot_2020-04-19 Natron](https://user-images.githubusercontent.com/5672810/79709946-81eec880-8291-11ea-8a9b-72f0fbd3da87.jpg)

Still gotta work out the news section and the footer and then I'll be ready to start on some of the other pages.  I'll probably start on the about page next and use it to display a more in-depth look into some of Natron's features.  https://wilkinson.graphics/NatronGitHub.github.io/

**Comment by Shrinks99** [comment]
Got the homepage in a usable state!  Tweaks can be made but it's largely representative of its final look.  The footer and hero section still need some work.

![Screenshot_2020-04-26 Natron](https://user-images.githubusercontent.com/5672810/80324361-8de10a00-87fe-11ea-808b-019f7105caca.jpg)

Preview is still available [here](https://wilkinson.graphics/NatronGitHub.github.io/), do y'all like this?  Should I keep working on it? :P

**Comment by blackearth2014** [comment]
Looks good to me. Let me know how this new site will benefit old and new
users of Natron.

Omar

**Comment by pomboverso** [comment]
> Got the homepage in a usable state! Tweaks can be made but it's largely representative of its final look. The footer and hero section still need some work.
> 
> Preview is still available [here](https://wilkinson.graphics/NatronGitHub.github.io/), do y'all like this? Should I keep working on it? :P
>
> https://wilkinson.graphics/NatronGitHub.github.io/

Looks pretty good [Shrinks99](https://github.com/Shrinks99) :)

I wonder if the header should have like a animated video since is a landing page for FX software. I'm willing to provide some animations using CSS (or three.js if it make sense)

**Comment by Shrinks99** [comment]
Currently the plan is to use images from the community that are actually created in the software.  I think an animated looping video of some impressive shots made with Natron would be very neat but perhaps something to explore post-release?

As for an update on this issue (I forgot it existed haha, the site looks a LOT different now) please see my [project board](https://github.com/Shrinks99/NatronGitHub.github.io/projects/1?query=is%3Aopen+sort%3Aupdated-desc) for details on the site's completion, with the exception of some copy changes it's in a position to be rolled out sans feature pages! :D

**Comment by rodlie** [comment]
Closing this, see https://github.com/NatronGitHub/NatronGitHub.github.io/pull/96
