### ISSUE TITLE
Download links mismatch

### ISSUE THREAD

**Issue by cgvirus** [NatronGitHub/NatronGitHub-legacy-website#25]
Hi folks, the current download links are corrupted. I am not sure about the current strings. Let me know. Thanks. @devernay

**Comment by devernay** [comment]
was
`https://github.com/NatronGitHub/Natron/releases/download/2.3.14/Natron-2.3.14-Windows-x86_64bit-setup.exe`
now
`https://github.com/NatronGitHub/Natron/releases/download/v2.3.14/Natron-2.3.14-Windows-x86_64bit-setup.exe`

The v was added to all the release tags to conform to common practices. Can you update the web site?

**Comment by cgvirus** [comment]
Alright. Done. Thanks.
