### ISSUE TITLE
SEO Brute force needed

### ISSUE THREAD

**Issue by cgvirus** [NatronGitHub/NatronGitHub-legacy-website#5]
Hi @devernay  It seems to be a good time to make this site SEO friendly. I believe [this](https://adadevelopment.github.io/other/create-site-github-pages.html ) will give the site proper SEO. As it needs personal involvement I believe you are the best to hold the power to this.

**Comment by blackearth2014** [comment]
Fred is not on Facebook anymore because of his job. I will pass this
information along via email.

**Comment by devernay** [comment]
I did that a few days ago (thus the sitemap.txt), I'll check again in a few days if it gets processed. Fahad and Omar, can you please send me the email corresponding to your google account so that can add you as owners too?

**Comment by devernay** [comment]
to my email: frederic.devernay at m4x dot org

**Comment by cgvirus** [comment]
Hi my mail is contact.fahadpathik at gmail dot com
Let me known please if something is needed. Thanks

**Comment by blackearth2014** [comment]
My email address is vegaseditor@gmail.com

**Comment by devernay** [comment]
OK, added you both with full permissions in https://search.google.com/search-console?resource_id=https://natrongithub.github.io/
Good news, natron.fr doesn't seem to appear in google searches, and natrongithub.github.io appears instead. I'm closing this issue.

**Comment by cgvirus** [comment]
All set. Confirmed. Thanks!

**Comment by blackearth2014** [comment]
Thanks Fred
