### ISSUE TITLE
fix security issues

### ISSUE THREAD

**Issue by devernay** [NatronGitHub/NatronGitHub-legacy-website#6]
https://github.com/NatronGitHub/NatronGitHub.github.io/network/alerts
@cgvirus can you please take care of this? I know nothing about npm etc.
Thank you

**Comment by cgvirus** [comment]
Hopefully it's fixed now. I can't see the alerts in this repo BTW. Updated my old repo with this one. 
Let me know. Thanks.

**Comment by devernay** [comment]
thanks, fixed!
also added you as admin. can you get the (now empty) ls-ist of alerts by following the above link?

**Comment by blackearth2014** [comment]
I will check later today.

**Comment by cgvirus** [comment]
@devernay yes. Now it's showing. Thanks.
